name: Code gen tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Use OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_URL: https://api.deepseek.com/beta
          OPENAI_API_MODEL: deepseek-chat
        run: |
          echo "Generating test script"
          python ai_coding.py tests/test.toml
          bash test.sh ai_coding.py 2>&1 | tee result.txt

      - name: Upload artifact test.sh
        uses: actions/upload-artifact@v2
        with:
          name: test.sh
          path: test.sh

      - name: Upload artifact helloworld.py
        uses: actions/upload-artifact@v2
        with:
          name: helloworld.py
          path: helloworld.py

      - name: Upload artifact qsort.py
        uses: actions/upload-artifact@v2
        with:
          name: qsort.py
          path: qsort.py

      - name: Upload artifact askllm.py
        uses: actions/upload-artifact@v2
        with:
          name: askllm.py
          path: askllm.py

      - name: Upload result.txt
        uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt
