name: Selfgen tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install ai_coding
        run: |
          python setup.py develop

      - name: run test
        env:
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_URL: https://api.deepseek.com/beta
          OPENAI_API_MODEL: deepseek-reasoner
        run: |
          echo "Generating ai_coder script"
          ai_coding self/ai_coder.toml
          echo "==================="
          echo "Showing ai_coder script"
          echo "-------------------"
          cat ai_coder.py
          echo "==================="
          echo "Generating test script"
          python ai_coder.py tests/test.toml
          echo "==================="
          echo "Showing test script"
          echo "-------------------"
          cat test.sh
          echo "==================="
          echo "Running test"
          bash test.sh ai_coder.py 2>&1 |tee $GITHUB_STEP_SUMMARY
          echo "==================="
          echo "Showing helloworld script"
          echo "-------------------"
          cat helloworld.py
          echo "==================="
          echo "==================="
          echo "Showing qsort script"
          echo "-------------------"
          cat qsort.py
          echo "==================="
          echo "==================="
          echo "Showing askllm script"
          echo "-------------------"
          cat askllm.sh
          echo "==================="
